### ISSUE TITLE
Deprecate Grunt and JSHint in favor of Gulp and eslint

### ISSUE THREAD

**Issue by owap** [OpenWhere/landscapes.io#41]
Gulp shipped with the MeanJS upgrade, and we now have both gruntfiles and gulp files.
The MeanJS upgrade also deprecated jshint in favor of eslint.

We should perhaps also consider upgrading our eslint file to follow the same standards as an industry leader, such as Google or AirBnB

https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

**Comment by matthewfincher** [comment]
OBE
