### ISSUE TITLE
Add Webpack and ES6 transpiling

### ISSUE THREAD

**Issue by owap** [OpenWhere/landscapes.io#43]
The current front-end code loads dozens of individual javascript files, and developers do not have the ability to take advantage of ES6 features.  Implementing Webpack with a Babel transpiler will solve both of these problems, and confer additional benefits such as hot module reloading, which will further increase developer productivity

**Comment by matthewfincher** [comment]
https://github.com/OpenWhere/landscapes.io/tree/v2
